CREATE TABLE TOURNAMENTS (
  NAME                TEXT PRIMARY KEY,
  TYPE                TEXT NOT NULL,
  MAX_SIZE            INT  NOT NULL,
  FINISHED            INT  NOT NULL DEFAULT 0,
  REGISTRATION_CLOSED INT  NOT NULL DEFAULT 0,
  CURRENT_ROUND       INT  NOT NULL DEFAULT 1
);

CREATE TABLE STATS (
  ID  INT PRIMARY KEY AUTOINCREMENT,
  KEY TEXT NOT NULL UNIQUE
);

CREATE TABLE PARTICIPANTS (
  ID PRIMARY KEY AUTOINCREMENT,
  NAME      TEXT NOT NULL,
  TYPE      TEXT NOT NULL
);

CREATE TABLE MATCHES (
  ID              INT AUTOINCREMENT,
  PARTICIPANT_ID  INT,
  SCORE           INT NOT NULL DEFAULT 0,
  MATCH_COMPLETED INT NOT NULL DEFAULT 0,
  PRIMARY KEY (ID, PARTICIPANT_ID),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE TOURNAMENTS_PARTICIPANTS (
  TOURNAMENT_NAME TEXT,
  PARTICIPANT_ID  INT,
  PRIMARY KEY (TOURNAMENT_NAME, PARTICIPANT_ID),
  FOREIGN KEY (TOURNAMENT_NAME) REFERENCES TOURNAMENTS (NAME),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE TOURNAMENTS_STATS (
  TOURNAMENT_NAME TEXT,
  STAT_ID         INT,
  WINNING_STAT    INT NOT NULL DEFAULT 0,
  PRIMARY KEY (TOURNAMENT_NAME, STAT_ID),
  FOREIGN KEY (TOURNAMENT_NAME) REFERENCES TOURNAMENTS (NAME),
  FOREIGN KEY (STAT_ID) REFERENCES STATS (ID)
);

CREATE TABLE TOURNAMENTS_MATCHES (
  TOURNAMENT_NAME TEXT,
  MATCH_ID        INT,
  PRIMARY KEY (TOURNAMENT_NAME, MATCH_ID),
  FOREIGN KEY (TOURNAMENT_NAME) REFERENCES TOURNAMENTS (NAME),
  FOREIGN KEY (MATCH_ID) REFERENCES MATCHES (ID)
);

CREATE TABLE PARTICIPANTS_TEAMS (
  PARTICIPANT_ID INT PRIMARY KEY,
  LOGO_PATH      TEXT NOT NULL,
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE PARTICIPANTS_PEOPLE (
  PARTICIPANT_ID INT,
  EMAIL          TEXT,
  PHONE_NUMBER   TEXT,
  TEAM_ID        INT,
  PRIMARY KEY (PARTICIPANT_ID, TEAM_ID, EMAIL, PHONE_NUMBER),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID),
  FOREIGN KEY (TEAM_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE PARTICIPANTS_CAPTAINS (
  PARTICIPANT_ID INT PRIMARY KEY,
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS_PEOPLE (PARTICIPANT_ID)
);

CREATE TABLE PARTICIPANTS_STATS (
  PARTICIPANT_ID INT,
  STAT_KEY       TEXT,
  STAT_VALUE     INT NOT NULL DEFAULT 0,
  PRIMARY KEY (PARTICIPANT_ID, STAT_KEY),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);
