CREATE TABLE TOURNAMENTS (
  NAME                TEXT PRIMARY KEY,
  TYPE                TEXT NOT NULL,
  MAX_SIZE            INTEGER  NOT NULL,
  FINISHED            INTEGER  NOT NULL DEFAULT 0,
  REGISTRATION_CLOSED INTEGER  NOT NULL DEFAULT 0,
  CURRENT_ROUND       INTEGER  NOT NULL DEFAULT 1
);

CREATE TABLE STATS (
  ID  INTEGER PRIMARY KEY AUTOINCREMENT,
  KEY TEXT NOT NULL UNIQUE
);

CREATE TABLE PARTICIPANTS (
  ID   INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  TYPE TEXT NOT NULL --Player (One of possible subclasses) or Team
);

CREATE TABLE MATCHES (
  ID              TEXT,
  PARTICIPANT_ID  INTEGER,
  MATCH_COMPLETED INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (ID, PARTICIPANT_ID),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE TOURNAMENTS_PARTICIPANTS (
  TOURNAMENT_NAME TEXT,
  PARTICIPANT_ID  INTEGER,
  RANKING         INTEGER,
  PRIMARY KEY (TOURNAMENT_NAME, PARTICIPANT_ID),
  FOREIGN KEY (TOURNAMENT_NAME) REFERENCES TOURNAMENTS (NAME),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE TOURNAMENTS_STATS (
  TOURNAMENT_NAME TEXT,
  STAT_ID         INTEGER,
  WINNING_STAT    INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (TOURNAMENT_NAME, STAT_ID),
  FOREIGN KEY (TOURNAMENT_NAME) REFERENCES TOURNAMENTS (NAME),
  FOREIGN KEY (STAT_ID) REFERENCES STATS (ID)
);

CREATE TABLE TOURNAMENTS_MATCHES (
  TOURNAMENT_NAME TEXT,
  MATCH_ID        INTEGER,
  PRIMARY KEY (TOURNAMENT_NAME, MATCH_ID),
  FOREIGN KEY (TOURNAMENT_NAME) REFERENCES TOURNAMENTS (NAME),
  FOREIGN KEY (MATCH_ID) REFERENCES MATCHES (ID)
);

CREATE TABLE PARTICIPANTS_TEAMS (
  PARTICIPANT_ID INTEGER PRIMARY KEY,
  LOGO_PATH      TEXT,
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE PARTICIPANTS_PEOPLE (
  PARTICIPANT_ID INTEGER,
  EMAIL          TEXT,
  PHONE_NUMBER   TEXT,
  TEAM_ID        INTEGER,
  PRIMARY KEY (PARTICIPANT_ID, TEAM_ID, EMAIL, PHONE_NUMBER),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID),
  FOREIGN KEY (TEAM_ID) REFERENCES PARTICIPANTS (ID)
);

CREATE TABLE PARTICIPANTS_CAPTAINS (
  PARTICIPANT_ID INTEGER PRIMARY KEY,
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS_PEOPLE (PARTICIPANT_ID)
);

CREATE TABLE PARTICIPANTS_STATS (
  PARTICIPANT_ID INTEGER,
  STAT_KEY       TEXT,
  STAT_VALUE     INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (PARTICIPANT_ID, STAT_KEY),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (ID)
);
